export const GET_PROVINCE = "GET_PROVINCE";
export const GET_TRIP_BY_USER = "GET_TRIP_BY_USER";
export const SELECT_TRIP = "SELECT_TRIP";
export const GET_TRIP_PASSENGER = "GET_TRIP_PASSENGER";
export const GET_IMG_VEHICLES = "GET_IMG_VEHICLES";
export const OPEN_CLOSE_DETAILS = "OPEN_CLOSE_DETAILS";
export const OPEN_CLOSE_BOOKING = "OPEN_CLOSE_BOOKING";
export const SELECT_BOOKING_SEAT = "SELECT_BOOKING_SEAT";
export const TRIP_RENDER = "TRIP_RENDER";
export const SET_DROPOFF_PICKUP = "SET_DROPOFF_PICKUP";

export const GET_TRIP_PASSENGER2 = "GET_TRIP_PASSENGER2";

export const SET_SORT_TIME = "SET_SORT_TIME";
export const CANCEL_SORT_TIME = "CANCEL_SORT_TIME";
