export const SET_LOADING = "SET_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const SET_LOADING_BUTTON = "SET_LOADING_BUTTON";
export const HIDE_LOADING_BUTTON = "HIDE_LOADING_BUTTON";

export const SET_LOADING_SPIN = "SET_LOADING_SPIN";
export const HIDE_LOADING_SPIN = "HIDE_LOADING_SPIN";

export const SET_LOADING_SPIN_FILTER = "SET_LOADING_SPIN_FILTER";
export const HIDE_LOADING_SPIN_FILTER = "HIDE_LOADING_SPIN_FILTER";

export const SET_RESULT = "SET_RESULT";
export const HIDE_RESULT = "HIDE_RESULT";
