export const SET_LIST_PASSENGER = "SET_LIST_PASSENGER";
export const SET_DETAIL_PASSENGER = "SET_DETAIL_PASSENGER";
export const PREVIEW_TRUE = "PREVIEW_TRUE";
export const PREVIEW_FALSE = "PREVIEW_FALSE";
