export const SET_POINT_PICKUP = "SET_POINT_PICKUP";
export const SET_POINT_DROPOFF = "SET_POINT_DROPOFF";
export const SET_POINT = "SET_POINT";
export const SET_POINT_DETAIL = "SET_POINT_DETAIL";
export const SET_ADDRESS_POINT = "SET_ADDRESS_POINT";
export const SET_POINTPICK_DETAIL = "SET_POINTPICK_DETAIL";
export const SET_POINTDROP_DETAIL = "SET_POINTDROP_DETAIL";
