export const SET_TICKET_USER = "SET_TICKET_USER";
export const SET_LIST_TICKET = "SET_LIST_TICKET";
export const SET_DETAIL_TICKET = "SET_DETAIL_TICKET";
export const SET_LIST_TICKET_TRIP = "SET_LIST_TICKET_TRIP";
export const TICKET_BOOKING = "TICKET_BOOKING";
export const CHANGE_PICK_TICKET = "CHANGE_PICK_TICKET";
export const CHANGE_DROP_TICKET = "CHANGE_DROP_TICKET";
