export const GET_TRIP = "GET_TRIP";
export const GET_DETAIL_TRIP = "GET_DETAIL_TRIP";
export const GET_DETAIL_TRIPPASSENGER = "GET_DETAIL_TRIPPASSENGER";

export const GET_TRIP_PASSENGER = "GET_TRIP_PASSENGER";
export const SET_TRIP_CREATE = "SET_TRIP_CREATE";
export const SET_TRIPPASSENGER_CREATE = "SET_TRIPPASSENGER_CREATE";

export const FILTER_TRIPPASSENGER_TIME = "FILTER_TRIPPASSENGER_TIME";
