export const SET_LIST_VEHICLE = "SET_LIST_VEHICLE";
export const SET_VEHICLE_DETAIL = "SET_VEHICLE_DETAIL";
export const SET_FILELIST = "SET_FILELIST";
export const CANCEL_PREVIEW = "CANCEL_PREVIEW";
export const HANDLE_PREVIEW = "HANDLE_PREVIEW";
export const HANDLE_CHANGE_FILE = "HANDLE_CHANGE_FILE";

export const GET_DETAIL_SEAT = "GET_DETAIL_SEAT";
export const GET_IMAGE_VEHICLE = "GET_IMAGE_VEHICLE";
export const GET_SEAT_VEHICLE = "GET_SEAT_VEHICLE";
export const SET_VEHICLE_SELECT = "SET_VEHICLE_SELECT";
